guest/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve
from sign import views, test_tools
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^$', views.index),
    url(r'^admin', admin.site.urls),
    url(r'^api/list/filter', views.api_list_filter),
    url(r'^api/list/', views.api_list),
    url(r'^api/add/save/', views.api_add_save),
    url(r'^api/add$', views.api_add),
    url(r'^api/edit/', views.api_edit),
    url(r'^api_detail/', views.api_detail),
    url(r'^run_test/', views.run_test),
    url(r'^case/list/filter/', views.case_list_filter),
    url(r'^case/list/', views.case_list),
    url(r'^case/add/save/', views.case_add_save),
    url(r'^case/add/', views.case_add),
    url(r'^case/edit/', views.case_edit),
    url(r'^schedule/add/', views.schedule_add),
    url(r'^schedule/list/filter/', views.schedule_list_filter),
    url(r'^schedule/list/', views.schedule_list),
    url(r'^schedule/delete/', views.schedule_delete),
    url(r'^schedule/run/', views.schedule_run),
    url(r'^dependency/list/filter/', views.deependency_list_filter),
    url(r'^dependency/list/', views.deependency_list),
    url(r'^api/report/', views.api_report),
    url(r'^test_tools/', views.test_tools),
    url(r'^tools_button/', views.tools_button),
]

sign/models.py
from django.db import models
import datetime
# Create your models here.
from django.core.files.storage import FileSystemStorage

# fs = FileSystemStorage(location='/case')


class apis(models.Model):
    id = models.AutoField('ID', max_length=5, primary_key=True)
    path = models.URLField('接口路径', max_length=100, null=True)
    name = models.CharField('接口名称', max_length=200)
    method = models.CharField(max_length=10, choices=(('POST', 'POST'), ('GET', 'GET')), default='POST')    # choices=（value,display_name）
    content_type = models.CharField('数据传输方式', max_length=50, choices=(('JSON', 'JSON'), ('APPLICATION/X-WWW-FROM-URLENCODED', 'APPLICATION/X-WWW-FROM-URLENCODED')), default='JSON', null=True)
    belong_project = models.CharField('所属项目', max_length=20, choices=(('OC', 'OC'), ('PC', 'PC'), ('UC', 'UC'), ('SP', 'SP'), ('Odoo', 'Odoo')), default='OC')
    params = models.TextField('接口参数', max_length=5000)
    create_time = models.DateTimeField('创建时间', auto_now_add=True)
    update_time = models.DateTimeField('更新时间', auto_now=True)
    status = models.BooleanField('状态')

    class Meta:
        verbose_name = "接口列表"
        verbose_name_plural = "接口列表"

    def __str__(self):
        return self.name


class Case(models.Model):
    id = models.AutoField('ID', max_length=5, primary_key=True)
    name = models.CharField('用例名称', max_length=200)
    belong_project = models.CharField('所属项目', max_length=20, choices=(('OC', 'OC'), ('PC', 'PC'), ('UC', 'UC'), ('SP', 'SP'), ('Odoo', 'Odoo')), default='OC')
    description = models.CharField(max_length=200)
    file_name = models.FileField('文件名', null=True)
    create_time = models.DateTimeField('创建时间', auto_now_add=True)
    update_time = models.DateTimeField('更新时间', auto_now=True)
    status = models.BooleanField('状态')


class Dependency(models.Model):
    id = models.AutoField('ID', max_length=5, primary_key=True)
    param = models.CharField('参数名', max_length=50, unique=True)
    value = models.CharField('参数值', max_length=500)
    create_time = models.DateTimeField('创建时间', auto_now_add=True)
    update_time = models.DateTimeField('更新时间', auto_now=True)


class Schedule(models.Model):
    # 测试任务表
    id = models.AutoField('ID', max_length=5, primary_key=True)
    name = models.CharField('任务名', max_length=50, unique=True)
    env = models.CharField('环境', max_length=20)
    case_ids = models.CharField('用例ID', max_length=500)
    last_do_time = models.DateTimeField('上次执行时间', null=True)
    schedule_status = models.CharField('执行状态', max_length=10, default='未执行')
    do_times = models.IntegerField('执行次数', default=0)
    status = models.BooleanField('状态', default=True)
    create_time = models.DateTimeField('创建时间', auto_now_add=True)
    update_time = models.DateTimeField('更新时间', auto_now=True)


class RunRecord(models.Model):
    # 执行记录表
    id = models.AutoField('ID', max_length=5, primary_key=True)
    schedule_ids = models.CharField('执行任务ID', max_length=500)
    total_count = models.IntegerField('用例总数', default=0)
    success_count = models.IntegerField('成功数', default=0)
    fail_count = models.IntegerField('失败数', default=0)
    spend_time = models.CharField('执行时间', max_length=50)
    schedule_result = models.CharField('执行结果', max_length=20, choices=(('Success', '成功'), ('Fail', '失败')))
    sequence = models.CharField('执行序列号', max_length=100, null=True)
    create_time = models.DateTimeField('创建时间', auto_now_add=True)
    update_time = models.DateTimeField('更新时间', auto_now=True)

sign/views.py
# coding:utf-8
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from sign.models import apis, Case, Dependency, Schedule, RunRecord
import requests, xlrd,xlwt, json, os
from django.core.paginator import Paginator
from django.core import serializers
from django.contrib import messages
from sign.test_tools import TestTools
import datetime
import decimal
from sign.config.path import api_case_file_dir
from sign.API_Test.create_scripts import Create


def index(request):
    """index首页"""
    return render(request, 'base.html') #返回获取的数据行


def paginate(objs, page=1):
    """重新封装分页器"""
    paginator = Paginator(objs, 20)     # 分页器对象,每页大小为20
    total_pages = paginator.num_pages       # 总页数
    list= paginator.page(page).object_list   # 当前请求页case列表
    r = {'current_page': page, 'total_pages': total_pages, 'list': list}
    return r


def api_list(request):
    """接口列表页"""
    flag = request.GET.get('flag', '')
    message = request.GET.get('message', '')
    api_obj = apis.objects.all().order_by('-id')  # 通过objects这个模型管理器的all()获得apis表中所有数据行，相当于SQL中的SELECT * FROM

    page = request.GET.get('page', 1)       # 取请求的页码，默认值为首页1
    result = paginate(api_obj, page)

    if flag and message:
        result.update({'flag': flag, 'message': message})
        return render(request, 'api_list.html', result)
    else:
        return render(request, 'api_list.html', result)


def api_list_filter(request):
    """接口列表筛选器"""
    print(request.GET.copy())
    api_address = request.GET.get('search_address', '')
    api_name = request.GET.get('search_name', '')
    api_belong_project = request.GET.get('search_belong_project', '')
    origin_data = {'api_address': api_address, 'api_name': api_name, 'api_belong_project': api_belong_project}

    api_list = apis.objects.filter(path__contains=api_address, name__contains=api_name, belong_project__contains=api_belong_project).order_by('-id')
    print(api_list)
    page = request.GET.get('page', 1)       # 取请求的页码，默认值为首页1
    result = paginate(api_list, page)
    result.update({'origin_data': origin_data})
    return render(request, 'api_list.html', result)     # 返回获取的数据行


def api_detail(request):
    """接口详情页"""
    id = request.GET.get('id')
    api = apis.objects.get(id=id)   # 获取单个对象，通过id值获取数据行
    return render(request, 'api_detail.html', {'api': api})


def api_add(request):
    return render(request, 'api_add.html')


def api_add_save(request):
    try:
        print(request.POST.copy())
        name = request.POST.get('api_name')
        belong_project = request.POST.get('api_belong_project')
        address = request.POST.get('api_address')
        method = request.POST.get('api_method')
        content_type = request.POST.get('api_content_type', '')
        params = request.POST.get('body').strip()

        if method == 'POST':
            if content_type == 'JSON':  # JSON格式body需要先JSON化再存入数据库
                params = json.dumps(eval(params))   # 去除params空格和换行符，并转为Json格式
        ob = apis.objects.create(name=name, belong_project=belong_project, path=address, method=method, content_type=content_type, params=params, status=True)
    except Exception as e:
        print(e)
        return HttpResponseRedirect('/api/list/?flag=fail&message=添加失败： internal error')
    else:
        return HttpResponseRedirect('/api/list/?flag=success&message=添加成功')


def api_edit(request):
    operation = request.GET.get('operation')
    id = request.GET.get('id')
    api = apis.objects.get(id=id)

    if operation == 'query':    # 编辑-详情页
        return render(request, 'api_edit.html', {'api': api})

    elif operation == 'save':   # 保存更改
        print(request.POST.copy())
        name = request.POST.get('api_name')
        belong_project = request.POST.get('api_belong_project')
        address = request.POST.get('api_address')
        method = request.POST.get('api_method')
        content_type = request.POST.get('api_content_type', '')
        params = request.POST.get('body').strip()

        if method == 'POST':
            if content_type == 'JSON':  # JSON格式body需要先JSON化再存入数据库
                params = json.dumps(eval(params))   # 去除params空格和换行符，并转为Json格式
        try:
            # api = apis.objects.filter(id=id)
            # api.update(name=name, belong_project=belong_project, address=address, method=method, content_type=content_type, params=body)
            api.name = name
            api.belong_project = belong_project
            api.path = address
            api.method = method
            if method == 'POST':
                api.content_type = content_type
            elif method == 'GET':
                api.content_type = ''
            api.params = params
            api.save()
        except Exception as e:
            print(e)
            return HttpResponseRedirect('/api/list/?flag=fail&message=更新失败： internal error')
        else:
            return HttpResponseRedirect('/api/list/?flag=success&message=更新成功')
    elif operation == 'delete':
        try:
            api.delete()
        except Exception as e:
            print(e)
            return HttpResponseRedirect('/api/list/?flag=fail&message=删除失败： internal error')
        else:
            return HttpResponseRedirect('/api/list/?flag=success&message=删除成功')


def case_list(request):
    flag = request.GET.get('flag', '')
    message = request.GET.get('message', '')

    cases_obj = Case.objects.all().order_by('-id')  # 通过objects这个模型管理器的all()获得apis表中所有数据行，相当于SQL中的SELECT * FROM

    page = request.GET.get('page', 1)  # 取请求的页码，默认值为首页1
    result = paginate(cases_obj, page)

    if flag and message:
        result.update({'flag': flag, 'message': message})
        return render(request, 'case_list.html', result)
    else:
        return render(request, 'case_list.html', result)


# def case_list_paginator(request):
#     # json_request = json.loads(request)
#     # page = json_request.get('page', 1)
#     # page_size = json_request.get('page_size', 1)
#     page = request.GET.get('page', 1)
#     page_size = request.GET.get('page_size', 1)
#     cases = Case.objects.all().order_by('-id')
#     paginator = Paginator(cases, page_size)
#     total_pages = paginator.num_pages
#     case_list = paginator.page(page).object_list

    # 返回Json格式数据实现Ajax分页
    # response_case = []
    # for case in case_list:
    #     response_case.append({'case_id': case.id, 'case_name': case.name, 'case_desc': case.description, 'case_create_time': case.create_time.strftime("%Y-%m-%d %H:%M:%S"), 'case_status': case.status, 'file_name': str(case.file_name)})
    # response = {'page_count': page_count, 'response_case': response_case}
    # print(response)
    # return HttpResponse(json.dumps(response))
    # return render(request, 'case_list.html', {'cases': case_list, 'total_pages': total_pages, 'current_page': page})


def case_list_filter(request):
    """用例筛选器"""
    print(request.GET.copy())
    case_desc = request.GET.get('search_desc', '')
    case_name = request.GET.get('search_name', '')
    origin_data = {'case_desc': case_desc, 'case_name': case_name}
    case_list = Case.objects.filter(description__contains=case_desc, name__contains=case_name).order_by('-id')
    print(case_list)
    page = request.GET.get('page', 1)       # 取请求的页码，默认值为首页1
    result = paginate(case_list, page)
    result.update({'origin_data': origin_data})
    return render(request, 'case_list.html', result)     # 返回获取的数据行


def case_add(request):
    return render(request, 'case_add.html')


def case_add_save(request):
    case_name = request.POST.get('case_name')
    case_desc = request.POST.get('case_desc')
    case_file = request.FILES.get("case_file")
    case_belong_project = request.POST.get('case_belong_project')
    print(request.POST.copy())
    file_name = datetime.datetime.now().strftime('%Y%m%d%H%M%S') + case_file.name
    f = open(api_case_file_dir+file_name, 'wb+')
    for chunk in case_file.chunks():
        f.write(chunk)
    f.close()
    try:
        ob = Case.objects.create(name=case_name,belong_project=case_belong_project, description=case_desc, file_name=file_name, status=True)
    except Exception as e:
        print(e)
        return HttpResponseRedirect('/case/list/?flag=fail&message=添加失败： internal error')
    else:
        return HttpResponseRedirect('/case/list/?flag=success&message=添加成功')


def case_edit(request):
    operation = request.GET.get('operation')
    id = request.GET.get('id')
    case = Case.objects.get(id=id)

    if operation == 'query':    # 编辑-详情页
        return render(request, 'case_edit.html', {'case': case})

    elif operation == 'save':   # 保存更改
        case_name = request.POST.get('case_name')
        case_desc = request.POST.get('case_desc')
        case_file = request.FILES.get('case_file')
        case_belong_project = request.POST.get('case_belong_project')
        print(request.POST.copy(), '\n', case_file)

        if case_file:       # 有文件上传才存储文件
            file_name = datetime.datetime.now().strftime('%Y%m%d%H%M%S') + case_file.name
            f = open(api_case_file_dir + file_name, 'wb+')
            for chunk in case_file.chunks():
                f.write(chunk)
            f.close()
        try:
            case.name = case_name
            case.description = case_desc
            case.belong_project = case_belong_project
            if case_file:
                case.file_name = file_name      # 有新的文件上传才更新file_name
            case.save()
        except Exception as e:
            print(e)
            return HttpResponseRedirect('/case/list/?flag=fail&message=更新失败： internal error')
        else:
            return HttpResponseRedirect('/case/list/?flag=success&message=更新成功')
    elif operation == 'delete':
        try:
            case.delete()
        except Exception as e:
            print(e)
            return HttpResponseRedirect('/case/list/?flag=fail&message=删除失败： internal error')
        else:

sign/templates/api_add.html
{% extends './base.html' %}
{% block main-content %}

<ul class="breadcrumb">
    <li><a href="/api/list/">接口列表</a> </li>
    <li>添加接口</li>
</ul>

<div class="panel">
    <div class="panel-heading">
        <h3 class="panel-title">添加接口</h3>
    </div>
    <div class="panel-body">
        <div class="form-horizontal">
            <form action="/api/add/save/" method="post" onsubmit="return check()" id="api_add_form">
                <div class="form-group">
                    <label class="control-label col-md-2">接口名称</label>
                    <div class="col-md-6">
                        <input class="form-control" name="api_name">
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">所属项目</label>
                    <div class="col-md-6">
                        <select class="form-control" name="api_belong_project">
                            <option value="">请选择</option>
                            <option value="OC">OC</option>
                            <option value="PC">PC</option>
                            <option value="UC">UC</option>
                            <option value="SP">SP</option>
                            <option value="Odoo">Odoo</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">接口路径</label>
                    <div class="col-md-6">
                        <input class="form-control" name="api_address">
                    </div>
                </div>
                <div class="form-group" id="api_method">
                    <label class="control-label col-md-2">请求方式</label>


                    <div class="col-md-1 control-label">
                        <label class="fancy-radio">
                            <input name="api_method" value="GET" type="radio" onclick="removeApiType(this)"><span><i></i>GET</span>
                        </label>
                    </div>
                    <div class="col-md-1 control-label">
                        <label class="fancy-radio">
                            <input name="api_method" value="POST" type="radio" onclick="removeApiType(this)"><span><i></i>POST</span>
                        </label>
                    </div>
                </div>
                <div class="form-group" id="api_content_type">
                    <label class="control-label col-md-2">数据传输方式</label>
                    <div class="col-md-6">
                        <select class="form-control" name="api_content_type" onclick="changetag(this)">
                            <option value="">请选择</option>
                            <option value="JSON">JSON</option>
                            <option value="APPLICATION/X-WWW-FROM-URLENCODED">APPLICATION/X-WWW-FROM-URLENCODED</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2" id="label">请求Body</label>
                    <div class="col-md-6" id="params">
                        <textarea name="body" id="textarea" class="form-control" placeholder='' rows="3"></textarea>
                    </div>
                </div>
                <div id="toastr-demo" class="container col-md-5 pull-left" >
                    <button type="submit" class="btn btn-primary pull-right">保存</button>
                </div>
            </form>


        </div>
    </div>
</div>

{% block script %}
<script>
    function removeApiType(option) {
        var api_content_type = $("#api_content_type")
        if(option.value=='GET'){
            if(api_content_type.length>0){
                api_content_type.remove()
            }
        }

        {#如果api_content_type长度为0则添加html(用length是否为0判断元素是否存在，因为元素不存在时选择器也会取得值，只是长度为0)#}
        if(option.value=='POST'){
            if(api_content_type.length==0){
                api_content_type = " <div class=\"form-group\" id=\"api_content_type\">\n" +
                    "                    <label class=\"control-label col-md-2\">数据传输方式</label>\n" +
                    "                    <div class=\"col-md-6\">\n" +
                    "                        <select class=\"form-control\" name=\"api_content_type\" onclick=\"changetag(this)\">\n" +
                    "                            <option value=\"\">请选择</option>\n" +
                    "                            <option value=\"JSON\">JSON</option>\n" +
                    "                            <option value=\"APPLICATION/X-WWW-FROM-URLENCODED\">APPLICATION/X-WWW-FROM-URLENCODED</option>\n" +
                    "                        </select>\n" +
                    "                    </div>\n" +
                    "                </div>"
                $("#api_method").after(api_content_type)
            }
        }
    }
</script>

<script>
    function changetag(option) {
        if(option.value=='JSON'){
            $('#textarea').attr('placeholder', '请输入JSON格式，如：{“login_name": ""}')
            {#$('#params').append('<textarea id="textarea" class="form-control" placeholder=\'请输入JSON格式数据，如：{“login_name": ""}\' rows="3"></textarea>');#}
        }
        if(option.value=='APPLICATION/X-WWW-FROM-URLENCODED'){
            $('#textarea').attr('placeholder', '请输入表单格式参数，以逗号分隔，如：login_name,login_password')
        }
        else {
            console.log(option.value)
        }
    }
</script>
    
    <script>
        function check() {
            var form = new FormData(document.getElementById("api_add_form"));
            var api_name = form.get('api_name');
            var api_belong_project = form.get('api_belong_project')
            var api_address = form.get('api_address')
            var api_method = form.get('api_method')
            var api_content_type = form.get('api_content_type')
            var body = form.get('body')
            console.log(api_name, api_belong_project, api_address, api_method, api_content_type, body)
            tag_div = $("#alert")
            if(tag_div) {
                tag_div.remove()
            }
            if(api_method=="GET"){
                api_content_type = true
            }
            if (!(api_name && api_belong_project && api_address && api_method && api_content_type && body)){
                danger_div = '<div id="alert" class="alert alert-danger alert-dismissable" width="20"><button type="button" class="close" data-dismiss="alert">×</button>必填项不能为空</div>'
                $('.breadcrumb').before(danger_div)
                return false
            }
            else {
                return true
            }
        }
    </script>
{% endblock %}

{% endblock %}

sign/templates/api_detail.html
{% extends "./base.html" %}
{% block main-content %}

<ul class="breadcrumb">
    <li><a href="/api/list/">接口列表</a> </li>
    <li>接口详情</li>
</ul>

<div class="panel">
    <div class="panel-body">
      <div class="table-responsive">
          <table class="table">
              <thead>
                <tr>
                  <th><strong>ID</strong></th>
                  <th><strong>接口名称</strong></th>
                  <th><strong>接口路径</strong></th>
                  <th><strong>数据传输方式</strong></th>
                  <th><strong>POST/GET</strong></th>
                  <th><strong>创建时间</strong></th>
                  <th><strong>状态</strong></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>{{api.id}}</td>
                  <td>{{api.name}}</td>
                  <td>{{api.path}}</td>
                  <td>{{api.content_type}}</td>
                  <td>{{api.method}}</td>
                  <td>{{api.create_time|date:"Y-m-d H:i:s"}}</td>
                  <td>{{api.status}}</td>
                </tr>
              </tbody>
        </table>
      </div>
      <div class="panel">
          <form action="/run_test/"method="post" enctype="multipart/form-data" id="form-model" class="form-horizontal">
              <div class="panel-heading">接口参数</div>
              <div class="panel-body">
                  <div class="form-group" style="display:none">
                       <label class="control-label col-md-1">ID</label>
                       <div class="col-md-6">
                          <input name="id" type="text" value="{{api.id}}" class="form-control">
                       </div>
                  </div>
                  <div class="col-md-7">
                      <textarea name="data" id="data" class="form-control" rows="10">{{ api.params }}</textarea>
                  </div>
                  <div id="toastr-demo" class="container col-md-7 pull-left" >
                      <button type="button" onclick="send_data()" class="btn btn-primary pull-right">Go</button>
                  </div>
              </div>
      </div>
          </form>
{#          <div id="toastr-demo" class="col-md-6 pull-left" >#}
{#              <button type="button" id="submit_btn" onclick="go()" class="btn btn-primary btn-toastr pull-right" data-context="info" data-message='' data-position="top-right">Go</button>#}
{#          </div>#}
      </div>
    </div>
</div>

{% block script %}
<script>
function send_data(){
    var form = new FormData(document.getElementById("form-model"));
    $.ajax({
        url:"/run_test/",
        type:"post",
        data:form,
        async : false,
        processData:false,
        contentType:false,
        success : function(response_data) {
            result = response_data
            tag_div = $("#alert")
            if(tag_div){
                tag_div.remove()
            }
            if(result){
                {#$("#submit_btn").attr("data-context", 'info')#}
                success_div = '<div id="alert" class="alert alert-success alert-dismissable" width="20"><button type="button" class="close" data-dismiss="alert">×</button>'+result+'</div>'
                $('.breadcrumb').before(success_div)
            }
            else {
                danger_div = '<div id="alert" class="alert alert-danger alert-dismissable" width="20"><button type="button" class="close" data-dismiss="alert">×</button>'+result+'</div>'
                $('.breadcrumb').before(danger_div)
            }
        }
    });
}
</script>

<script>
var txt = document.getElementById("data")
if(txt){
    $(document).ready(
    function format_json() {
        var params = {{ api.params | safe }}   // |safe关闭django自动转译
        var apiData = JSON.stringify(params, null, 4);
        $("#data").text(apiData)
    }
)
}
</script>
{% endblock %}

{% endblock %}

sign/templates/api_report.html
{% extends 'base_list.html' %}

{% block li %}
<li>
    <a href="#subPages" data-toggle="collapse" class="active"><i class="lnr lnr-file-empty"></i> <span>接口自动化</span> <i class="icon-submenu lnr lnr-chevron-left"></i></a>
    <div id="subPages" class="collapse in">
        <ul class="nav">
            <li><a href="/api/list/" class="">接口列表</a></li>
            <li><a href="/case/list/" class="">用例列表</a></li>
            <li><a href="/schedule/list/" class="">测试任务</a></li>
            <li><a href="/api/report/" class="active">测试报告</a></li>
            <li><a href="/dependency/list/" class="">全局参数</a></li>
        </ul>
    </div>
</li>
{% endblock %}

{% block list-body %}

    <div class="container-fluid">
        <div class="col-md-2 pull-left">
            <ul class="breadcrumb">
                <li>测试报告</li>
            </ul>
        </div>
    </div>
    <div class="panel">
        <div class="panel-body">
{#            <form method="get" action="/schedule/list/filter/">#}
{#                <div class="row">#}
{#                    <div class="form-group pull-right">#}
{#                        <button type="submit" class="btn btn-primary"><span class="fa fa-search"></span></button>#}
{#                        <a type="button" class="btn btn-primary" onclick="btn_reset()"><span class="lnr lnr-trash"></span></a>#}
{#                    </div>#}
{##}
{#                    <div class="col-sm-2 pull-right">#}
{#                        <div class="form-group">#}
{#                            <select class="form-control" name="search_schedule_status" id="schedule_status">#}
{#                                <option value="">请选择</option>#}
{#                                <option value="待执行">待执行</option>#}
{#                                <option value="执行中">执行中</option>#}
{#                                <option value="完毕">完毕</option>#}
{#                            </select>#}
{#                        </div>#}
{#                    </div>#}
{#                    <div class="col-sm-2 pull-right">#}
{#                        <div class="form-group">#}
{#                            <select class="form-control" name="search_env" id="env">#}
{#                                <option value="">请选择</option>#}
{#                                <option value="test">test</option>#}
{#                                <option value="staging">staging</option>#}
{#                                <option value="production">production</option>#}
{#                            </select>#}
{#                        </div>#}
{#                    </div>#}
{#                    <div class="col-sm-2 pull-right">#}
{#                        <div class="form-group">#}
{#                            <input name="search_name" type="text" value="{{ origin_data.name }}" class="form-control form-control" placeholder="任务名">#}
{#                        </div>#}
{#                    </div>#}
{##}
{#                </div>#}
{#            </form>#}

            <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th class="text-left" width="20">
                    <input type="checkbox" id="checkbox-ifs" onclick="changeBox(this)" value="0">
                  </th>
                  <th><strong>执行任务ID</strong></th>
                  <th><strong>用例总数</strong></th>
                  <th><strong>成功数</strong></th>
                  <th><strong>失败数</strong></th>
                  <th><strong>执行时间</strong></th>
                  <th><strong>执行结果</strong></th>
                  <th><strong>创建时间</strong></th>
                  <th><strong>更新时间</strong></th>
                  <th><strong>查看报告</strong></th>
                </tr>
              </thead>
                <tbody>
                {%for api_record in list%}
                    <tr>
                      <td>
                        <input type="checkbox" class="checkbox-ifs" value={{api_record.id}} name="checkbox_id">
                      </td>
                      <td>{{api_record.schedule_ids}}</td>
                      <td>{{api_record.total_count}}</td>
                      <td>{{api_record.success_count}}</td>
                      <td>{{api_record.fail_count}}</td>
                      <td>{{api_record.spend_time}}</td>
                      <td>{{api_record.get_schedule_result_display}}</td>   <!--get_字段_display：显示翻译值-->
                      <td>{{api_record.create_time|date:"Y-m-d H:i:s"}}</td>
                      <td>{{api_record.update_time|date:"Y-m-d H:i:s"}}</td>
                      <td>
                          <a href="/static/api_test_file/api_test_report/{{ api_record.sequence }}Report.html"><span class="fa fa-eye"></span>&nbsp;&nbsp;</a>
                      </td>
                    </tr>
                {%endfor%}
              </tbody>
            </table>
            </div>
        </div>
    </div>

{% endblock %}

{% block base_list_script %}

<script type="text/javascript">
  function changeBox(box){
    var boxs = document.getElementsByClassName('checkbox-ifs');
    if(box.checked){
       for (i=0; i<boxs.length; i++){
            document.getElementsByClassName('checkbox-ifs')[i].checked = true;
       }
    }else{
       for (i=0; i<boxs.length; i++){
           document.getElementsByClassName('checkbox-ifs')[i].checked = false;
       }
    }
  }
</script>

{#<script>#}
{#//保持环境/执行状态为选中值#}
{#var filter_env = "{{ origin_data.env }}"#}
{#var filter_schedule_status = "{{ origin_data.schedule_status }}"#}
{#if(filter_env){#}
{#    $(document).ready(#}
{#    function set_env() {#}
{#        $("#env").val(filter_env)#}
{#    }#}
{#)#}
{#}#}
{#if(filter_schedule_status){#}
{#    $(document).ready(#}
{#    function set_schedule_status() {#}
{#        $("#schedule_status").val(filter_schedule_status)#}
{#    }#}
{#)#}
{#}#}
{#</script>#}

{% endblock %}